config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :comments, only: %i[new create destroy]
  # Users routes
  resource :user_profile, only: %i[show edit update]
  get '/show_per_assign/:id', to: 'user_profiles#show_per_assign', as: 'user_profile_per_assign_tasks'
  get '/show_per_approve/:id', to: 'user_profiles#show_per_approve', as: 'user_profile_per_approve_tasks'
  get '/show_approved/:id', to: 'user_profiles#show_approved', as: 'user_profile_approved_tasks'
  get '/take_out_user/:id', to: 'user_profiles#take_out_user', as: 'take_out_user'
  put '/edit_ajax', to: 'user_profiles#edit_ajax', as: 'edit_ajax'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Landing route
  get 'landing/without_house'
  get 'landing/landing_page'
  root to: 'landing#landing_page'

  # House routes
  resources :houses, only: %i[new create show destroy]
  get 'join', to: 'houses#join'
  post 'join_house', to: 'houses#join_house'
  get 'leave_house', to: 'houses#leave_house'
  # Task routes
  resources :tasks
  get 'finish_task/:id', to: 'tasks#finish_task', as: 'finish_task'
  get 'reject_task/:id', to: 'tasks#reject_task', as: 'reject_task'
  get 'approve_task/:id', to: 'tasks#approve_task', as: 'approve_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  skip_before_action :redirect_if_no_house, only: %i[new create join join_house]
  before_action :set_house, only: %i[show]

  def new
    @house = House.new
  end

  def show
    @q = @house.house_tasks(current_user).ransack(params[:q])
    @house_tasks = @q.result(distinct: true)
  end

  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        current_user.house_id = @house.id
        current_user.owner = true
        current_user.save
        format.html { redirect_to @house, notice: 'la casa ha sido creada con èxito.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def join; end

  def join_house
    @house = House.find_by(code: params[:code])
    if @house.blank?
      redirect_to join_path(notice: 'El codigo de la casa es incorrecto.')
    else
      respond_to do |format|
        current_user.house_id = @house.id
        if current_user.save
          format.html { redirect_to @house, notice: 'Te has unido a la casa.' }
          # format.json { render :show, status: :created, location: @house }
        else
          format.html { render :new, status: :unprocessable_entity }
          # format.json { render json: @house.errors, status: :unprocessable_entity }
        end
        format.js
      end
    end
  end

  def leave_house
    @house = House.find_by(id: current_user.house_id)
    current_user.change_ownership_tasks
    current_user.unassign_tasks
    current_user.house_id = nil
    respond_to do |format|
      if current_user.save
        format.html { redirect_to landing_without_house_path, notice: 'Has dejado la casa.' }
        # format.json { render :show, status: :created, location: @house }
      else
        format.html { redirect_to landing_without_house_path, status: :unprocessable_entity }
        # format.json { render json: @house.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def destroy
    if current_user.owner?
      @house = House.find_by(id: current_user.house_id)
      @house.close_house
      current_user.owner = false
      current_user.save
      @house.destroy
      respond_to do |format|
        format.html { redirect_to landing_without_house_path, notice: 'La casa ha sido eliminada.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to user_profile_path, notice: 'No eres el dueño de la casa.' }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_house
    @house = House.find(params[:id])
  end

  def house_params
    params.require(:house).permit(:name, :code, :q)
  end
end

app/helpers/houses_helper.rb
# frozen_string_literal: true

module HousesHelper
end

app/views/houses/_search_form.html.erb
<%= search_form_for @q, url: house_path(@house) do |f| %>

  <p class="mb-1 task-text"><%= f.label :aasm_state_eq, 'Busca las tareas según su Estado' %></p>
  <%= f.select(:aasm_state_eq, options_for_select([['Por asignar', :created], ['Asignado', :assigned],
                                                   ['Finalizado', :finished]]), {:include_blank => 'Todas'}) %>
  <%= f.submit 'Buscar', class:"search-btn"%>
  <% end %>
    <%# Estableceré estos arreglos estaticos para el MPV [['Por asignar', :created], ['Asignado', :assigned], ['Finalizado', :finished], ['Aprobado', :approved]]
     Mejorar para la siguiente version Task.aasm.states.map(&:name)%>

app/views/houses/join.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container-fluid join-house-top">
    <h2>Unirme a una casa</h2>
    <h4>Ingresa el código de la casa a la que te unirás</h4>
    <%= form_with(url: join_house_path, local: true)  do |f| %>
      <div class="form-control input_user p-0 mt-4">
        <%= f.text_field :code, autofocus: true, class:"form-control input_user p-2 border-0" %>
      </div>
      <%= f.submit "Unirse", class: "btn join-house-top-button p-2"%>
    <% end %>
      <h3 class="mt-5">Al unirte a una casa como residente tendrás la posibilidad de:</h3>
    <div class="container-fluid join-house-bottom">
      <div>
        <p><span class="mt-2"><i class="fas fa-home fa-1x"></i>   Crear nuevas tareas para tí y tus hommies.</span></p>
        <p><span class="mt-2"><i class="fas fa-home fa-1x"></i>   Administrar tus tareas desde tu perfil.</span></p>
        <p><span class="mt-2"><i class="fas fa-home fa-1x"></i>   Dejar la casa cuando quieras y unirte a una nueva.</span></p>
      </div>
    </div>
    <%= link_to 'Regresar', landing_without_house_path %>
  </div>

  <%= render "shared/footer" %>
</body>

app/views/houses/new.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container-fluid new-house-top">
    <h2>Crear un casa nueva</h2>
    <h4>Ingresa el nombre de tu nuevo hogar</h4>
    <%= form_with(model: @house, local: true)  do |f| %>
      <div class="form-control input_user p-0 mt-4">
        <%= f.text_field :name, autofocus: true, placeholder: 'La Baticueva', class:"form-control input_user p-2 border-0" %>
      </div>
      <%= f.submit "Crear", class: "btn new-house-top-button p-2"%>
    <% end %>
      <h3 class="mt-5">Recuerda que al crear la casa tendrás privilegios especiales</h3>

    <div class="container-fluid new-house-bottom">
      <div>
        <p><span class="mt-2"><i class="fas fa-home fa-1x"></i>   Podrás darle el código de tu hogar a otros y formar una familia.</span></p>
        <p><span class="mt-2"><i class="fas fa-home fa-1x"></i>   Podrás sacar a cualquier miembro de la casa.</span></p>
        <p><span class="mt-2"><i class="fas fa-home fa-1x"></i>   Serás el único que podrá clausurar el casa que has creado.</span></p>
      </div>
      
    </div>
      <%= link_to 'Regresar', landing_without_house_path %>
  </div>

  <%= render "shared/footer" %>
</div>

app/views/houses/show.html.erb
<body class="d-flex flex-column min-vh-100">
<div class="container mt-5 mb-4">

    <h1 class="mt-3 task-text">Bienvenido a <%= @house.name%> </h1>
    <div class="row">
    <div class="col">
      <%= render 'houses/search_form.html.erb' %>
    </div>
    <div class="col d-flex align-self-start justify-content-end">
      <button type="button" class="btn new-task-btn">
        <%= link_to 'Listado de tareas', tasks_path,  class:"btn px-0" %>
      </button>
    </div>
    <div class="d-flex justify-content-center mt-5">
        <h2 class="task-text">Tareas pendientes </h2>
    </div>

    <div class="mt-5">
      <table class="table table-striped">
        <tr>
          <th><%= sort_link(@q, :name, "Nombre", {default_order: :asc}, {class: "sort-link-color"})%></th>
          <th>Descripción</th>
          <th>Categoria</th>
          <th><%= sort_link(@q, :aasm_state, "Estado", {default_order: :asc}, {class: "sort-link-color"})%></th>
          <th>Fecha limite</th>
          <th>Fecha fin</th>
          <th>Fecha de aprobacion</th>
          <th>Asignado a</th>
          <th>Creado por</th>
          <th>Aprobado por</th>
          <th>Acciones</th>
        </tr>
        <% @house_tasks.each do |task|%>
          <tr>
          <td><%= task.name%></td>
          <td><%= task.description%></td>
          <td><%= task.category%></td>
          <td>
            <%= 'Sin asignar' if task.created?%>
            <%= 'Asignada' if task.assigned?%>
            <%= 'Por aprobar' if task.finished?%>
            <%= 'Aprobada' if task.approved?%>
          </td>
          <td><%= task.limit_date.strftime('%d/%m/%Y')%></td>
          <% if task.finished_date.nil?%>
            <td> </td>
          <% else %>
            <td><%= task.finished_date.strftime('%d/%m/%Y')%></td>
          <% end %>
          <% if task.approved_date.nil?%>
            <td > </td>
          <% else %>
            <td><%= task.approved_date.strftime('%d/%m/%Y')%></td>
          <% end %>
          <td><%= task.assignee%></td>
          <td><%= task.owner%></td>
          <td><%= task.reviewer%></td>
          <td class="actions-style"><%= link_to 'Abrir', task %></td>
          </tr>
        <% end %>
      </table>
      <% if @house_tasks.empty? %>
      <div class="d-flex justify-content-center">
        <p class="task-text">No se encontraron resultados</p>
      </div>
    <% end %>
    </div>
  </div>
</div>
  <%= render "shared/footer" %>
</body>