config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :comments, only: %i[new create destroy]
  # Users routes
  resource :user_profile, only: %i[show edit update]
  get '/show_per_assign/:id', to: 'user_profiles#show_per_assign', as: 'user_profile_per_assign_tasks'
  get '/show_per_approve/:id', to: 'user_profiles#show_per_approve', as: 'user_profile_per_approve_tasks'
  get '/show_approved/:id', to: 'user_profiles#show_approved', as: 'user_profile_approved_tasks'
  get '/take_out_user/:id', to: 'user_profiles#take_out_user', as: 'take_out_user'
  put '/edit_ajax', to: 'user_profiles#edit_ajax', as: 'edit_ajax'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Landing route
  get 'landing/without_house'
  get 'landing/landing_page'
  root to: 'landing#landing_page'

  # House routes
  resources :houses, only: %i[new create show destroy]
  get 'join', to: 'houses#join'
  post 'join_house', to: 'houses#join_house'
  get 'leave_house', to: 'houses#leave_house'
  # Task routes
  resources :tasks
  get 'finish_task/:id', to: 'tasks#finish_task', as: 'finish_task'
  get 'reject_task/:id', to: 'tasks#reject_task', as: 'reject_task'
  get 'approve_task/:id', to: 'tasks#approve_task', as: 'approve_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include AASM

  belongs_to :house
  belongs_to :owner, class_name: 'User', inverse_of: :owned_tasks
  belongs_to :assignee, class_name: 'User', inverse_of: :assigned_tasks, optional: true
  belongs_to :reviewer, class_name: 'User', inverse_of: :reviewed_tasks, optional: true
  has_many :comments, dependent: :destroy
  has_many :comenting_users, { through: :comments, source: :user }

  aasm do
    state :created, initial: true
    state :assigned, :finished, :approved

    event :assign do
      transitions from: :created, to: :assigned
    end

    event :finish do
      transitions from: :assigned, to: :finished
    end

    event :unassign do
      transitions from: :assigned, to: :created
    end

    event :approve do
      transitions from: :finished, to: :approved
    end
    event :reject do
      transitions from: :finished, to: :assigned
    end
  end

  validates :name, :description, :category, :limit_date, presence: true
  # Validación de soft delete
  acts_as_paranoid
  # Enum de categorías de tareas
  enum category: { 'Limpieza' => 0, 'Cocina' => 1, 'Compras' => 2, 'Mascota' => 3 }
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy finish_task approve_task reject_task]

  def index
    @house = House.find_by(id: current_user.house_id)
    @q = @house.tasks.all.ransack(params[:q])
    @tasks = @q.result(distinct: true)
  end

  def show
    @house = House.find_by(id: current_user.house_id)
    @comments = Comment.where(task_id: @task.id).order('created_at DESC').page params[:page]
    @comment = Comment.new
  end

  def new
    @users = User.where(house_id: current_user.house_id)
    @task = Task.new
  end

  def create
    @task = Task.new(create_params)
    @task.owner_id = current_user.id
    @task.house_id = current_user.house_id
    @task.assign unless @task.assignee_id.nil?
    send_email unless @task.assignee_id.nil?
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'La tarea fue creada con éxito.' }
        # format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @culo.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @users = User.where(house_id: current_user.house_id)
  end

  def update
    @task.update(create_params)
    @task.assign if @task.created? && !@task.assignee_id.nil?
    @task.unassign if @task.assigned? && @task.assignee_id.nil?
    respond_to do |format|
      if @task.update(create_params)
        format.html { redirect_to @task, notice: 'La tarea ha sido actualizada.' }
        # format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @culo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    @house = current_user.house_id
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: 'La tarea ha sido eliminada.' }
      format.json { head :no_content }
    end
  end

  def finish_task
    @task.finish
    @task.finished_date = Time.current
    @task.save
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Has finalizado la tarea.' }
    end
  end

  def reject_task
    @task.reject
    @task.finished_date = nil
    @task.save
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Has rechazado la tarea.' }
    end
  end

  def approve_task
    @task.approve
    @task.approved_date = Time.current
    @task.reviewer_id = current_user.id
    @task.save
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Has aprobado la tarea.' }
    end
  end

  def send_email
    from = SendGrid::Email.new(email: 'kelvis.alvarez20@gmail.com')
    to = SendGrid::Email.new(email: @task.assignee.email)
    subject = 'Se te ha asignado una nueva tarea'
    content = SendGrid::Content.new(type: 'text/plain',
                                    value: 'Se ha creado una nueva tarea y ha sido asignada a ti, vamos a trabajar!')
    mail = SendGrid::Mail.new(from, subject, to, content)
    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
    Rails.logger.debug response.status_code
    Rails.logger.debug response.headers
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def create_params
    params.require(:task).permit(:name, :description, :category, :limit_date, :owner_id,
                                 :assignee_id)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, "Nombre", class:"mb-1 form-text" %>
    <%= form.text_field :name, autofocus: true, placeholder:"Sacar al perro", class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción", class:"mb-1 form-text" %>
    <%= form.text_area :description, placeholder:"¿De qué trata la tarea?", class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :category, "Categoría", class:"mb-1 form-text" %><br/>
    <%= form.select :category, Task.categories.keys, class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :limit_date, "Fecha límite", class:"mb-1 form-text" %><br/>
    <%= form.date_select :limit_date, start_year: Date.today.year, end_year: Date.today.year + 20, order: [:day, :month, :year], class:"form-control input_user p-2 border-0"%>
  </div>

  <div class="mb-3">
    <%= form.label :assignee, "Asignar a", class:"mb-1 form-text" %><br/>
    <%= form.collection_select(:assignee_id, @users, :id, :first_name, {include_blank: true}) %>
  </div>

  <div class="actions">
    <button type="button" class="btn back-btn">
      <%= link_to 'Volver', tasks_path, class:"btn px-0"  %>
    </button>
    <%= form.submit "Guardar", class:"btn task-btn" %>
    
  </div>
<% end %>

app/views/tasks/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <p class="mb-1 task-text"><%= f.label :aasm_state_eq, 'Busca las tareas según su Estado' %></p>
  <%= f.select(:aasm_state_eq, options_for_select([['Por asignar', :created], ['Asignado', :assigned],
                                                   ['Finalizado', :finished], ['Aprobado', :approved]]), {:include_blank => 'Todas'}) %>
  <%= f.submit 'Buscar', class:"search-btn"%>
  <% end %>
    <%# Estableceré estos arreglos estaticos para el MPV [['Por asignar', :created], ['Asignado', :assigned], ['Finalizado', :finished], ['Aprobado', :approved]]
     Mejorar para la siguiente version Task.aasm.states.map(&:name)%>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container new-task-container mb-4">
    <div class="card register-card">
      <div class="card-body mx-auto">
        <h4 class="card-title m-3 text-center">Editar la tarea seleccionada</h4>
        <%= form_for(@task, :url => {:action => 'update', :id => @task.id}) do |f| %>
          <%= render 'form', task: @task %>
        <% end %>
      </div> <!-- card.// -->
    </div>
  </div>
  <%= render "shared/footer" %>
</body>

app/views/tasks/index.html.erb
<body class="d-flex flex-column min-vh-100">
<div class="container mb-4">
  <div class="breadcrumbs">
    <%= link_to 'Volver a la casa', house_path(@house) %>
  </div>
    <h1 class="mt-3 task-text">Listado de tareas</h1>
    <div class="row">
    <div class="col">
      <%= render 'tasks/search_form.html.erb' %>
    </div>
    <div class="col d-flex align-self-start justify-content-end">
      <button type="button" class="btn new-task-btn">
        <%= link_to 'Nueva tarea', new_task_path,  class:"btn px-0 " %>
      </button>
    </div>


    <div class="mt-5">
      <table class="table table-striped">
        <tr>
          <th><%= sort_link(@q, :name, "Nombre", {default_order: :asc}, {class: "sort-link-color"})%></th>
          <th>Descripción</th>
          <th>Categoria</th>
          <th><%= sort_link(@q, :aasm_state, "Estado", {default_order: :asc}, {class: "sort-link-color"})%></th>
          <th>Fecha limite</th>
          <th>Fecha fin</th>
          <th>Fecha de aprobacion</th>
          <th>Asignado a</th>
          <th>Creado por</th>
          <th>Aprobado por</th>
          <th>Acciones</th>
        </tr>
        <% @tasks.each do |task|%>
          <tr>
          <td><%= task.name%></td>
          <td><%= task.description%></td>
          <td><%= task.category%></td>
          <td>
            <%= 'Sin asignar' if task.created?%>
            <%= 'Asignada' if task.assigned?%>
            <%= 'Por aprobar' if task.finished?%>
            <%= 'Aprobada' if task.approved?%>
          </td>
          <td><%= task.limit_date.strftime('%d/%m/%Y')%></td>
          <% if task.finished_date.nil?%>
            <td> </td>
          <% else %>
            <td><%= task.finished_date.strftime('%d/%m/%Y')%></td>
          <% end %>
          <% if task.approved_date.nil?%>
            <td> </td>
          <% else %>
            <td><%= task.approved_date.strftime('%d/%m/%Y')%></td>
          <% end %>
          <td><%= task.assignee%></td>
          <td><%= task.owner%></td>
          <td><%= task.reviewer%></td>
          <td class="actions-style"><%= link_to 'Abrir', task %></td>
          </tr>
        <% end %>
      </table>
      <% if @tasks.empty? %>
      <div class="d-flex justify-content-center">
        <p class="task-text">No se encontraron resultados</p>
      </div>
    <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>
</body>

app/views/tasks/new.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container new-task-container my-4">
    <div class="card register-card">
      <div class="card-body mx-auto">
        <h4 class="card-title m-3 text-center">Crea una nueva tarea</h4>
        <%= render 'form', task: @task %>
      </div> <!-- card.// -->
    </div>
  </div>
  <%= render "shared/footer" %>
</body>

app/views/tasks/show.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container mb-3">
    <div class="breadcrumbs-task">
      <%= link_to 'Volver al listado de tareas', tasks_path %>
    </div>
    <div class="row">
      <div class="col-2 mt-5">
      </div>
      <div class="col-5 mt-5">
        <h1 class="task-text mb-5">Tarea: <%= @task.name %></h1>
        <h4 class="task-text">Descripción:</h4>
        <p class="task-text"> <%= @task.description %> </p>
      </div>
      <div class="col mt-5">
        <% if @task.owner_id == current_user.id %>
          <button type="button" class="btn edit-task-btn">
            <%= link_to 'Editar tarea', edit_task_path(@task),  class:"px-0" %>
          </button>
          <button type="button" class="btn delete-task-btn">
            <%= link_to 'Eliminar tarea', @task, method: :delete, data: { confirm: 'Estás seguro de eliminar la tarea?' }, class:"px-0" %>
          </button>
        <% end %>
    </div>

    <div class="row mt-2">
      <div class="col-2">
      </div>
      <div class="col-5">

        <div class="row">
          <div class="col-6">
            <h4 class="task-text">Categoría:</h4>
            <p class="task-text"> <%= @task.category %> </p>
          </div>

          <div class="col-6">
            <h4 class="task-text">Estado de la tarea:</h4>
            <p class="task-text">
              <%= 'Sin asignar' if @task.created?%>
              <%= 'Asignada' if @task.assigned?%>
              <%= 'Por aprobar' if @task.finished?%>
              <%= 'Aprobada' if @task.approved?%>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            <h4 class="task-text">Fecha límite:</h4>
            <p class="task-text"> <%= @task.limit_date.strftime('%d/%m/%Y') %> </p>
          </div>

          <div class="col-6">
            <h4 class="task-text">Tarea creada por:</h4>
            <p class="task-text">
              <% if @task.owner.avatar.attached?%>
              <span><%= image_tag(@task.owner.thumbnail_photo) %></span>
              <% else %>
                <%= image_tag 'default_avatar.png', class:"thumbnail_photo"%>
              <% end %>
              <span><%= @task.owner %></span>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-6">
            <h4 class="task-text">Tarea asignada a:</h4>
            <p class="task-text">
              <% if @task.assignee.nil? %>
                <span class="task-text">Sin asignar</span>
              <% else %>
                <% if @task.assignee.avatar.attached?%>
                  <span><%= image_tag(@task.assignee.thumbnail_photo) %></span>
                <% else %>
                  <%= image_tag 'default_avatar.png', class:"thumbnail_photo"%>
                <% end %>
                <span><%= @task.assignee %></span>
              <% end %>
              </p>
          </div>

          <div class="col-6">
            <% if @task.approved? %>
            <h4 class="task-text">Tarea aprobada por:</h4>
            <p class="task-text">
              <% if @task.reviewer.avatar.attached?%>
                  <span><%= image_tag(@task.reviewer.thumbnail_photo) %></span>
                <% else %>
                  <%= image_tag 'default_avatar.png', class:"thumbnail_photo"%>
                <% end %>
              <span><%= @task.reviewer %></span>
            </p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-5">
      </div>
    </div>

    <div class="d-flex justify-content-center mt-5">
      <% if @task.assigned? && current_user.id == @task.assignee_id %>
        <button type="button" class="btn finish-task-btn">
          <%= link_to 'Finalizar Tarea', finish_task_path(id: @task.id), class:"px-0" %>
        </button>

      <% elsif @task.finished? %>
        <% if @house.users.count == 1 %>
          <button type="button" class="btn reject-task-btn">
            <%= link_to 'Rechazar Tarea', reject_task_path(id: @task.id), class:"px-0" %>
          </button>
          <button type="button" class="btn approve-task-btn">
            <%= link_to 'Aprobar Tarea', approve_task_path(id: @task.id), class:"px-0" %>
          </button>
        <% elsif current_user.id != @task.assignee_id%>
          <button type="button" class="btn reject-task-btn">
            <%= link_to 'Rechazar Tarea', reject_task_path(id: @task.id), class:"px-0" %>
          </button>
          <button type="button" class="btn approve-task-btn">
            <%= link_to 'Aprobar Tarea', approve_task_path(id: @task.id), class:"px-0" %>
          </button>
        <% end %>
      <% end %>
    </div>

    <div class="mt-5">
      <h4 class="task-text">Comentarios</h4>
    </div>
      <section class="card bg-comments px-0 mb-5">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item ">
              <p class="nav-link">Escribe un comentario</p>
            </li>
          </ul>
        </div>
        <div class="card-comment">
          <div class="form-group">
            <%= render 'comments/form', comment: @comment %>
          </div>
        </div>
      </section>

      <% @comments.each do |comment|%>
        <section class="card bg-comments mb-3">
          <div class="row m-2">
            <div class="col-1">
              <span>
              <% if comment.user.avatar.attached?%>
              <%= image_tag(comment.user.thumbnail_photo) %>
              <% else %>
                <%= image_tag 'default_avatar.png', class:"thumbnail_photo"%>
              <% end %>
                
              </span>
            </div>
            <div class= "col-11 px-0">
              <div>
                <h5 class="text-capitalize task-text">
                  <%= comment.user.first_name %> <%= comment.user.last_name %>
                </h5>
                <p class="small text-secondary m-0 mt-1">
                  <%= time_ago_in_words(comment.created_at) %>
                </p>
              </div>
              <div>
                <p class="my-2">
                  <%= comment.content %>
                </p>
              </div>
            </div>
          </div>
          <hr class="my-1">
            <div class="my-1">
              <% (0...comment.images.count).each do |image| %>
                <%= image_tag(comment.comment_image_style(image)) %>
              <% end %>
              <% if (comment.images.count>0)%>
                <hr class="my-1">
              <% end %>
          </div>
          <div class="row m-2">
            <div class="col-7">
            </div>
            <div class="col-5 d-flex justify-content-end">
              <button type="button" class="btn delete-comment-btn">
                <%= link_to 'Eliminar', comment, method: :delete, data: { confirm: 'Estás seguro de eliminar el comentario?' }, class:"px-0" %>
              </button>
            </div>
          </div>
        </section>
      <% end %>

      <%= paginate @comments %>
    </div>
  </div>
  <%= render "shared/footer" %>
</body>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>