config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :comments, only: %i[new create destroy]
  # Users routes
  resource :user_profile, only: %i[show edit update]
  get '/show_per_assign/:id', to: 'user_profiles#show_per_assign', as: 'user_profile_per_assign_tasks'
  get '/show_per_approve/:id', to: 'user_profiles#show_per_approve', as: 'user_profile_per_approve_tasks'
  get '/show_approved/:id', to: 'user_profiles#show_approved', as: 'user_profile_approved_tasks'
  get '/take_out_user/:id', to: 'user_profiles#take_out_user', as: 'take_out_user'
  put '/edit_ajax', to: 'user_profiles#edit_ajax', as: 'edit_ajax'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Landing route
  get 'landing/without_house'
  get 'landing/landing_page'
  root to: 'landing#landing_page'

  # House routes
  resources :houses, only: %i[new create show destroy]
  get 'join', to: 'houses#join'
  post 'join_house', to: 'houses#join_house'
  get 'leave_house', to: 'houses#leave_house'
  # Task routes
  resources :tasks
  get 'finish_task/:id', to: 'tasks#finish_task', as: 'finish_task'
  get 'reject_task/:id', to: 'tasks#reject_task', as: 'reject_task'
  get 'approve_task/:id', to: 'tasks#approve_task', as: 'approve_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

class LandingController < ApplicationController
  skip_before_action :redirect_if_no_house

  def landing_page
    redirect_to landing_without_house_path if user_signed_in? && current_user.house_id.nil?
    redirect_to house_path(id: current_user.house_id) if user_signed_in? && current_user.house_id.present?
  end

  def without_house; end
end

app/helpers/landing_helper.rb
# frozen_string_literal: true

module LandingHelper
end

app/views/landing/index.html.erb
<h1>Usuario autenticado sin casa</h1>

<%= link_to 'Crear casa', new_house_path %>

<%= link_to 'Unirse a una casa', join_path %>

app/views/landing/landing_page.html.erb
<body class="d-flex flex-column min-vh-100">
	<div class="container-fluid home-main">
		<h2>My Hommies App</h2>
		<button type="button" class="btn btn-default">
			<%= link_to 'Registrate ya', new_user_registration_path, class: 'home-link' %>
		</button>
	</div>
	<div class="container-fluid home-content1">
		<div class="row">
			<div class="col-md-6 content1-left">
				<h3>Administra tus tareas del hogar</h3>
				<p>Crea, asigna y aprueba las tareas de tu hogar de manera fácil y rápida</p>
			</div>
			<div class="col-md-6 content1-right">
				<h3>Notifica a tus hommies</h3>
				<p>Envía correos a tus hommies al asignarles una tarea nueva.</p>
			</div>
		</div>
	</div>
	<%= render "shared/footer" %>
</body>

app/views/landing/without_house.html.erb
<body class="d-flex flex-column min-vh-100">
	<div class="container-fluid whouse-main">
		<h2>Bienvenido a My Hommies App</span></h2>
		<h3>¿Qué deseas hacer?</h3>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 wcontent1-left d-flex flex-column justify-content-center">
				<span class="d-flex justify-content-center"><i class="fas fa-home fa-7x"></i></span>
				<h3 class="d-flex justify-content-center">Crear una nueva casa</h3>
				<button type="button" class="btn whouse-main button p-2 mx-5">
					<%= link_to 'Crear', new_house_path, class: 'home-link' %>
				</button>
			</div>
			<div class="col-md-6 d-flex flex-column justify-content-center wcontent1-right">
				<span class="d-flex justify-content-center"><i class="fas fa-users fa-7x"></i></span>
				<h3 class="d-flex justify-content-center">Unirte a una casa</h3>
				<button type="button" class="btn whouse-main button p-2 mx-5">
					<%= link_to 'Unirte', join_path, class: 'home-link' %>
				</button>
			</div>
		</div>
	</div>
	<%= render "shared/footer" %>
</body>