config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :comments, only: %i[new create destroy]
  # Users routes
  resource :user_profile, only: %i[show edit update]
  get '/show_per_assign/:id', to: 'user_profiles#show_per_assign', as: 'user_profile_per_assign_tasks'
  get '/show_per_approve/:id', to: 'user_profiles#show_per_approve', as: 'user_profile_per_approve_tasks'
  get '/show_approved/:id', to: 'user_profiles#show_approved', as: 'user_profile_approved_tasks'
  get '/take_out_user/:id', to: 'user_profiles#take_out_user', as: 'take_out_user'
  put '/edit_ajax', to: 'user_profiles#edit_ajax', as: 'edit_ajax'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # Landing route
  get 'landing/without_house'
  get 'landing/landing_page'
  root to: 'landing#landing_page'

  # House routes
  resources :houses, only: %i[new create show destroy]
  get 'join', to: 'houses#join'
  post 'join_house', to: 'houses#join_house'
  get 'leave_house', to: 'houses#leave_house'
  # Task routes
  resources :tasks
  get 'finish_task/:id', to: 'tasks#finish_task', as: 'finish_task'
  get 'reject_task/:id', to: 'tasks#reject_task', as: 'reject_task'
  get 'approve_task/:id', to: 'tasks#approve_task', as: 'approve_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_profiles_controller.rb
# frozen_string_literal: true

class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: %i[show edit update edit_ajax show_per_assign
                                            show_per_approve show_approved]
  skip_before_action :verify_authenticity_token, only: %i[edit_ajax]

  def show
    # @my_tasks = @profile.my_tasks
    @my_pending_tasks = @profile.user_pending_tasks
    @house = House.find_by(id: @profile.house_id)
    @house_members = @house.house_members
    @tasks_grouped_by_state = @profile.my_tasks.group(:aasm_state).count
  end

  def show_per_assign
    @per_assign_tasks = @profile.user_per_assign_tasks
    @house = House.find_by(id: @profile.house_id)
    @house_members = @house.house_members
    @tasks_grouped_by_state = @profile.my_tasks.group(:aasm_state).count
  end

  def show_per_approve
    @per_approve_tasks = @profile.user_per_approve_tasks
    @house = House.find_by(id: @profile.house_id)
    @house_members = @house.house_members
    @tasks_grouped_by_state = @profile.my_tasks.group(:aasm_state).count
  end

  def show_approved
    @approved_tasks = @profile.user_approved_tasks
    @house = House.find_by(id: @profile.house_id)
    @house_members = @house.house_members
    @tasks_grouped_by_state = @profile.my_tasks.group(:aasm_state).count
  end

  def edit; end

  def update
    respond_to do |format|
      if @profile.update(user_profile_params)
        format.html { redirect_to user_profile_path, notice: 'Tu perfil se ha actualizado con éxito' }
        format.json { render :show, status: :ok, location: user_profile_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def take_out_user
    @house = House.find_by(id: current_user.house_id)
    @user = User.find(params[:id])
    @user.change_ownership_tasks
    @user.unassign_tasks
    @user.house_id = nil
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_profile_path, notice: 'Lo has sacado de la casa.' }
        # format.json { render :show, status: :created, location: @house }
      else
        format.html { redirect_to user_profile_path, status: :unprocessable_entity }
        # format.json { render(json: @house.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def edit_ajax
    birthdate_string = "#{params[:year_birthdate]}-#{params[:month_birthdate]}-#{params[:day_birthdate]}"
    birthdate = birthdate_string.to_datetime
    if @profile.update({ first_name: params[:first_name], last_name: params[:last_name], birthdate: birthdate })
      response = {
        first_name: @profile.first_name,
        last_name: @profile.last_name,
        birthdate: @profile.birthdate
      }
      render json: response, status: :ok
    else
      render json: { message: 'Ha ocurrido un error, intente de nuevo' }, status: :error
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_profile
    @profile = current_user
  end

  def user_profile_params
    params.require(:user).permit(:first_name, :last_name, :birthdate, :avatar)
  end

  def update_profile_params
    params.permit(:first_name, :last_name)
  end
end

app/helpers/user_profiles_helper.rb
# frozen_string_literal: true

module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_with(model: @profile, url: '#', method: :put, local: true) do |f| %>
  <div class="field mb-2">
    <%= f.label :first_name, "Nombre" %><br />
    <%= f.text_field :first_name, class: 'first_name_field form-control'  %>
  </div>

  <div class="field mb-2">
    <%= f.label :last_name, "Apellido" %><br />
    <%= f.text_field :last_name, class: 'last_name_field form-control' %>
  </div>

  <div class="field mb-2">
    <%= f.label :birthdate, "Fecha de nacimiento" %><br />
    <%= f.date_select :birthdate, order: [:day, :month, :year], class:"form-control" %>
  </div>
<% end %>

app/views/user_profiles/_form_photo.html.erb
 <%= form_with(model: @profile, url: user_profile_path, method: :put, local: true, multipart: true) do |f| %>

<div class="field d-flex justify-content-center edit-photo-container">
    <div class="input-group mb-3">
            <span class="input-group-text"><i class="fas fa-camera"></i></span>
            <div class="form-control input_user p-0 ">
              <%= f.file_field :avatar, class:"form-control input_user p-2 border-0"%>
            </div>
          </div>
  </div>

  <div class="actions">
    <%= f.submit "Cambiar", class:"btn edit-photo-btn" %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container-fluid edit-photo-top">
    <h2>Edita tu foto</h2>
    <div class="mb-5">
    <% if @profile.avatar.attached?%>
              <%= image_tag(@profile.edit_avatar_photo) %>
            <% else %>
              <%= image_tag 'default_avatar.png', class:"edit_avatar_photo"%>
            <% end %>
    </div>
    <%= form_for(@profile, :url => {:action => 'update', :id => @profile.id}, :html=> {:multipart => true }) do |f| %>
      <%= render 'form_photo', user: @profile %>
    <% end %>
      <div class="mt-2">
        <%= link_to 'Regresar', user_profile_path, class:"mt-4" %>
      </div>
  </div>

  <%= render "shared/footer" %>
</body>

app/views/user_profiles/show.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container emp-profile">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-img">
          <% if @profile.avatar.attached?%>
              <%= image_tag(@profile.profile_photo) %>
            <% else %>
              <%= image_tag 'default_avatar.png', class:"profile_photo"%>
            <% end %>
          <div class="edit-photo btn btn-primary px-0">
            <%= link_to 'editar foto', edit_user_profile_path, class:"profile-edit-photo-btn" %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="profile-head">
          <div class="mb-5">
            <h5 class="mb-3">
              <span id ='first_name'><%= @profile.first_name%></span>
              <span id ='last_name'><%= @profile.last_name%></span>
            </h5>
            <p class="profile-head-title mb-0">Fecha de nacimiento:</p>
            <span class="profile-head-text" id ='birthdate'><%= @profile.birthdate.strftime('%d/%m/%Y')%></span>
            <p class="profile-head-title mb-0 mt-2">Correo electrónico:</p>
            <span class="profile-head-text" id ='email'><%= @profile.email%></span>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <%= button_tag 'editar perfil', type: 'button', data: { bs_toggle: 'modal', bs_target: '#editUserModal' }, class:"profile-edit-btn" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="house-info">
          <div class="mb-3 house-info">
            <h5>Información de la casa</h5>
            <p class="profile-head-title mb-0">Nombre:</p>
            <span class="profile-head-text"><%= @profile.house.name%></span>
            <p class="profile-head-title mb-0">Código:</p>
            <span class="profile-head-text"><%= @profile.house.code%></span>
            <% if @profile.owner? %>
            <div class="mt-3">
              <h5>Hommies</h5>
            <div>
            </div>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th colspan="2"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @house_members.each do |member| %>
                    <tr>
                      <td class="mr-3"><%= member.first_name%> <%= member.last_name%></td>
                      <% if member.owner? %>
                        <td class="mb-5">
                          <button type="button" class="btn close-house-btn">
                            <%= link_to 'Cerrar', house_path(id: current_user.house_id), method: :delete, data: { confirm: 'Al cerrar la casa todas las tareas se borrarán y se sacará a los miembros de la casa. ¿Estás seguro de cerrar la casa?' }, class:'px-0' %>
                          </button>
                          <td>
                      <% else %>
                        <td>
                          <button type="button" class="btn kick-house-btn">
                            <%= link_to 'Sacar', take_out_user_path(id: member.id), data: { confirm: '¿Estás seguro de que deseas sacar a este miembro de la casa?' } %>
                          </button>
                        <td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <br>
            <% else %>
              <div class="d-flex justify-content-center mt-4">
                <button type="button" class="btn leave-house-btn">
                  <%= link_to 'Dejar casa', leave_house_path, data: { confirm: '¿Estás seguro de que deseas abandonar la casa?' }, class:'px-0' %>
                </button>
              </div>
            <% end %>
          </div>
          <div>
            <h5 class="d-flex justify-content-center">Cantidad de tareas por estado</h5>
            <%= pie_chart @tasks_grouped_by_state%>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-head">
          <ul class="nav nav-tabs">
              <li class="nav-item">
                  <%= link_to 'Pendientes', user_profile_path, class:"nav-link active" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Por asignar', user_profile_per_assign_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Por aprobar', user_profile_per_approve_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Aprobadas por mi', user_profile_approved_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
          </ul>
        </div>
        <div class="mt-5">
          <table class="table table-striped">
            <tr>
              <th>Nombre</th>
              <th>Categoria</th>
              <th>Fecha limite</th>
              <th>Creado por</th>
              <th class="d-flex justify-content-center">Acciones</th>
            </tr>
            <% @my_pending_tasks.each do |task|%>
              <tr>
              <td><%= task.name%></td>
              <td><%= task.category%></td>
              <td><%= task.limit_date.strftime('%d/%m/%Y')%></td>
              <td><%= task.owner%></td>
              <td class="actions-style"><%= link_to 'Abrir', task %></td>
              </tr>
            <% end %>
          </table>
          <% if @my_pending_tasks.empty? %>
            <div class="d-flex justify-content-center">
              <p class="task-text">No se encontraron resultados</p>
            </div>
          <% end %>
            </div>
          <br>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header ">
          <h5 class="modal-title" id="editUserModalLabel">Editar perfil</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id="editUserForm" class="modal-body">
          <%= render 'form', user: @profile %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="button" class="btn edit-modal-btn" id="update_button" >Guardar</button>
        </div>
      </div>
    </div>
  </div>
  
  <%# <%= link_to 'editar perfil', edit_user_profile_path %>
    <%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editUserModal">
    Launch demo modal
  </button>
    <%= link_to 'editar perfil', '#', 'data-bs-toogle': 'modal', 'data-bs-target': '#editUserModal' %>
  <%= render "shared/footer" %>
</body>

app/views/user_profiles/show_approved.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container emp-profile">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-img">
          <% if @profile.avatar.attached?%>
              <%= image_tag(@profile.profile_photo) %>
            <% else %>
              <%= image_tag 'default_avatar.png', class:"profile_photo"%>
            <% end %>
          <div class="edit-photo btn btn-primary px-0">
            <%= link_to 'editar foto', edit_user_profile_path, class:"profile-edit-photo-btn" %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="profile-head">
          <div class="mb-5">
            <h5 class="mb-3">
              <span id ='first_name'><%= @profile.first_name%></span>
              <span id ='last_name'><%= @profile.last_name%></span>
            </h5>
            <p class="profile-head-title mb-0">Fecha de nacimiento:</p>
            <span class="profile-head-text" id ='birthdate'><%= @profile.birthdate.strftime('%d/%m/%Y')%></span>
            <p class="profile-head-title mb-0 mt-2">Correo electrónico:</p>
            <span class="profile-head-text" id ='email'><%= @profile.email%></span>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <%= button_tag 'editar perfil', type: 'button', data: { bs_toggle: 'modal', bs_target: '#editUserModal' }, class:"profile-edit-btn" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="house-info">
          <div class="mb-3 house-info">
            <h5>Información de la casa</h5>
            <p class="profile-head-title mb-0">Nombre:</p>
            <span class="profile-head-text"><%= @profile.house.name%></span>
            <p class="profile-head-title mb-0">Código:</p>
            <span class="profile-head-text"><%= @profile.house.code%></span>
            <% if @profile.owner? %>
            <div class="mt-3">
              <h5>Hommies</h5>
            </div>
            <div>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th colspan="2"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @house_members.each do |member| %>
                    <tr>
                      <td class="mr-3"><%= member.first_name%> <%= member.last_name%></td>
                      <% if member.owner? %>
                        <td class="mb-5">
                          <button type="button" class="btn close-house-btn">
                            <%= link_to 'Cerrar', house_path(id: current_user.house_id), method: :delete, data: { confirm: 'Al cerrar la casa todas las tareas se borrarán y se sacará a los miembros de la casa. ¿Estás seguro de cerrar la casa?' }, class:'px-0' %>
                          </button>
                          <td>
                      <% else %>
                        <td>
                          <button type="button" class="btn kick-house-btn">
                            <%= link_to 'Sacar', take_out_user_path(id: member.id), data: { confirm: '¿Estás seguro de que deseas sacar a este miembro de la casa?' } %>
                          </button>
                        <td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <br>
            <% else %>
              <div class="d-flex justify-content-center mt-4">
                <button type="button" class="btn leave-house-btn">
                  <%= link_to 'Dejar casa', leave_house_path, data: { confirm: '¿Estás seguro de que deseas abandonar la casa?' }, class:'px-0' %>
                </button>
              </div>
            <% end %>
          </div>
          <div>
            <h5 class="d-flex justify-content-center">Cantidad de tareas por estado</h5>
            <%= pie_chart @tasks_grouped_by_state%>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-head">
          <ul class="nav nav-tabs">
              <li class="nav-item">
                  <%= link_to 'Pendientes', user_profile_path, class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Por asignar', user_profile_per_assign_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Por aprobar', user_profile_per_approve_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Aprobadas por mi', user_profile_approved_tasks_path(@profile), class:"nav-link active" %>
              </li>
          </ul>
        </div>
        <div class="mt-5">
          <table class="table table-striped">
            <tr>
              <th>Nombre</th>
              <th>Categoria</th>
              <th>Aprobada en</th>
              <th>Asignado a</th>
              <th class="d-flex justify-content-center">Acciones</th>
            </tr>
            <% @approved_tasks.each do |task|%>
              <tr>
              <td><%= task.name%></td>
              <td><%= task.category%></td>
              <td><%= task.approved_date.strftime('%d/%m/%Y')%></td>
              <td><%= task.assignee%></td>
              <td class="actions-style"><%= link_to 'Abrir', task %></td>
              </tr>
            <% end %>
          </table>
          <% if @approved_tasks.empty? %>
            <div class="d-flex justify-content-center">
              <p class="task-text">No se encontraron resultados</p>
            </div>
          <% end %>
            </div>
          <br>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header ">
          <h5 class="modal-title" id="editUserModalLabel">Editar perfil</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id="editUserForm" class="modal-body">
          <%= render 'form', user: @profile %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="button" class="btn edit-modal-btn" id="update_button" >Guardar</button>
        </div>
      </div>
    </div>
  </div>
  
  <%# <%= link_to 'editar perfil', edit_user_profile_path %>
    <%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editUserModal">
    Launch demo modal
  </button>
    <%= link_to 'editar perfil', '#', 'data-bs-toogle': 'modal', 'data-bs-target': '#editUserModal' %>
  <%= render "shared/footer" %>
</body>

app/views/user_profiles/show_per_approve.html.erb
<body class="d-flex flex-column min-vh-100">
  <div class="container emp-profile">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-img">
          <% if @profile.avatar.attached?%>
              <%= image_tag(@profile.profile_photo) %>
            <% else %>
              <%= image_tag 'default_avatar.png', class:"profile_photo"%>
            <% end %>
          <div class="edit-photo btn btn-primary px-0">
            <%= link_to 'editar foto', edit_user_profile_path, class:"profile-edit-photo-btn" %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="profile-head">
          <div class="mb-5">
            <h5 class="mb-3">
              <span id ='first_name'><%= @profile.first_name%></span>
              <span id ='last_name'><%= @profile.last_name%></span>
            </h5>
            <p class="profile-head-title mb-0">Fecha de nacimiento:</p>
            <span class="profile-head-text" id ='birthdate'><%= @profile.birthdate.strftime('%d/%m/%Y')%></span>
            <p class="profile-head-title mb-0 mt-2">Correo electrónico:</p>
            <span class="profile-head-text" id ='email'><%= @profile.email%></span>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <%= button_tag 'editar perfil', type: 'button', data: { bs_toggle: 'modal', bs_target: '#editUserModal' }, class:"profile-edit-btn" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="house-info">
          <div class="mb-3 house-info">
            <h5>Información de la casa</h5>
            <p class="profile-head-title mb-0">Nombre:</p>
            <span class="profile-head-text"><%= @profile.house.name%></span>
            <p class="profile-head-title mb-0">Código:</p>
            <span class="profile-head-text"><%= @profile.house.code%></span>
            <% if @profile.owner? %>
            <div class="mt-3">
              <h5>Hommies</h5>
            </div>
            <div>
              <table>
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th colspan="2"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @house_members.each do |member| %>
                    <tr>
                      <td class="mr-3"><%= member.first_name%> <%= member.last_name%></td>
                      <% if member.owner? %>
                        <td class="mb-5">
                          <button type="button" class="btn close-house-btn">
                            <%= link_to 'Cerrar', house_path(id: current_user.house_id), method: :delete, data: { confirm: 'Al cerrar la casa todas las tareas se borrarán y se sacará a los miembros de la casa. ¿Estás seguro de cerrar la casa?' }, class:'px-0' %>
                          </button>
                          <td>
                      <% else %>
                        <td>
                          <button type="button" class="btn kick-house-btn">
                            <%= link_to 'Sacar', take_out_user_path(id: member.id), data: { confirm: '¿Estás seguro de que deseas sacar a este miembro de la casa?' } %>
                          </button>
                        <td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <br>
            <% else %>
              <div class="d-flex justify-content-center mt-4">
                <button type="button" class="btn leave-house-btn">
                  <%= link_to 'Dejar casa', leave_house_path, data: { confirm: '¿Estás seguro de que deseas abandonar la casa?' }, class:'px-0' %>
                </button>
              </div>
            <% end %>
          </div>
          <div>
            <h5 class="d-flex justify-content-center">Cantidad de tareas por estado</h5>
            <%= pie_chart @tasks_grouped_by_state%>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-head">
          <ul class="nav nav-tabs">
              <li class="nav-item">
                  <%= link_to 'Pendientes', user_profile_path, class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Por asignar', user_profile_per_assign_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Por aprobar', user_profile_per_approve_tasks_path(@profile), class:"nav-link active" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Aprobadas por mi', user_profile_approved_tasks_path(@profile), class:"nav-link profile-tab-p" %>
              </li>
          </ul>
        </div>
        <div class="mt-5">
          <table class="table table-striped">
            <tr>
              <th>Nombre</th>
              <th>Categoria</th>
              <th>Finalizada en</th>
              <th>Asignado a</th>
              <th class="d-flex justify-content-center">Acciones</th>
            </tr>
            <% @per_approve_tasks.each do |task|%>
              <tr>
              <td><%= task.name%></td>
              <td><%= task.category%></td>
              <td><%= task.finished_date.strftime('%d/%m/%Y')%></td>
              <td><%= task.assignee%></td>
              <td class="actions-style"><%= link_to 'Abrir', task %></td>
              </tr>
            <% end %>
          </table>
          <% if @per_approve_tasks.empty? %>
            <div class="d-flex justify-content-center">
              <p class="task-text">No se encontraron resultados</p>
            </div>
          <% end %>
            </div>
          <br>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header ">
          <h5 class="modal-title" id="editUserModalLabel">Editar perfil</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id="editUserForm" class="modal-body">
          <%= render 'form', user: @profile %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="button" class="btn edit-modal-btn" id="update_button" >Guardar</button>
        </div>
      </div>
    </div>
  </div>
  
  <%# <%= link_to 'editar perfil', edit_user_profile_path %>
    <%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editUserModal">
    Launch demo modal
  </button>
    <%= link_to 'editar perfil', '#', 'data-bs-toogle': 'modal', 'data-bs-target': '#editUserModal' %>
  <%= render "shared/footer" %>
</body>